name: 'Ango CI CD Action'
description: 'Run basic Python CI / CD Tasks'
inputs:
  py-package:
    description: 'Root module that needs to be exported'
    required: true
runs:
  using: 'composite'
  steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Installing Dependencies
        shell: bash
        run: |
          pip install poetry
          poetry export -f requirements.txt --with dev | pip install -r /dev/stdin

      - name: Formatting & Linting
        shell: bash
        run: |
          python -m black . --config pyproject.toml --check --verbose 
          python -m isort . --settings pyproject.toml --check --verbose