name: Ango - Reusable Build & Deploy Workflow

on:
  workflow_call:
    inputs:
      app-name:
        description: Name of the Azure App service / Repo tag name
        required: true
        type: string

      app-environment:
        description: Environment to deploy the built app in.
        required: true
        type: string
        
      py-module:
        description: Python module that needs to be exported
        required: true
        type: string


concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: https://${{ secrets.REGISTRY_URL }}//
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.REGISTRY_URL }}/madlads-2k19/${{ inputs.app-name }}:latest
          file: Dockerfile
          build-args: |
            APP_NAME=${{ inputs.app-name }}
            PY_MODULE=${{ inputs.py-module }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ inputs.app-name }}
          slot-name: ${{ inputs.app-environment }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          images: ${{ secrets.REGISTRY_URL }}/madlads-2k19/${{ inputs.app-name }}:latest
